export const GET_SHOW_BY_ID_SUCCESS = 'GET_SHOW_BY_ID_SUCCESS';
export const GET_SHOW_BY_ID_FAIL = 'GET_SHOW_BY_ID_FAIL';

export const GET_EPISODE_BY_NUMBER_SUCCESS = 'GET_EPISODE_BY_NUMBER_SUCCESS';
export const GET_EPISODE_BY_NUMBER_FAIL = 'GET_EPISODE_BY_NUMBER_FAIL';

export const GET_EPISODES_BY_SHOW_SUCCESS = 'GET_EPISODES_BY_SHOW_SUCCESS';
export const GET_EPISODES_BY_SHOW_FAIL = 'GET_EPISODES_BY_SHOW_FAIL';
